[build-system]
requires = ["flit_core >=3.2,<4", "myst_parser"]
build-backend = "flit_core.buildapi"

[project]
name = "nwb-overview"
authors = [{name = "Ben Dichter", email = "ben.dichter@catalystneuro.com"}]
dynamic = ["version", "description"]
